import { describe, expect, it } from 'vitest';
import { Networks } from '@stellar/stellar-sdk';
import { p256 } from '@noble/curves/nist';
import { deriveAccountAddress, deriveSmartWalletAddress } from '../create';
import { encodeChallenge } from '../webauthn/clientData';
import { isKitError } from '../errors';

const FACTORY = 'CBVGSJEIKGQ6MYFOWCBNV2NLLPJJV757UP6QQV6FDTI4S3N72OZ676TM';
const CRED_DEMOCRED = Uint8Array.from(Buffer.from('64656d6f63726564', 'hex')); // "democred"
const PUB_A = p256.getPublicKey(new Uint8Array(32).fill(7), false); // 65-byte SEC-1
const PUB_B = p256.getPublicKey(new Uint8Array(32).fill(9), false);
// The real on-chain factoryDeployProof (contracts/deployments.json) is
// regenerated by the testnet redeploy of the v0.2 factory, whose salt binds the
// public key. Until that proof is refreshed, these tests assert the derivation
// scheme (determinism, sensitivity, the F1 key-binding, valid StrKey shape).

describe('deriveAccountAddress (deterministic C-address, no network)', () => {
  it('is deterministic and depends on the credential id', () => {
    const base = {
      factoryContractId: FACTORY,
      credentialId: CRED_DEMOCRED,
      publicKey: PUB_A,
      networkPassphrase: Networks.TESTNET,
    };
    const a = deriveAccountAddress(base);
    const again = deriveAccountAddress(base);
    const other = deriveAccountAddress({ ...base, credentialId: Uint8Array.from([9, 9, 9, 9]) });
    expect(again).toBe(a);
    expect(other).not.toBe(a);
    expect(a).toMatch(/^C[A-Z2-7]{55}$/); // a valid contract StrKey
  });

  it('cross-language KAT: matches the address the Rust factory deploys (F3 twin)', () => {
    // Same fixed inputs as the account-factory Rust test `address_kat_matches_sdk_derivation`
    // (KAT-1 key, credential "democred", the v0.2 testnet factory, testnet). Both sides
    // must land on the identical C-address, pinning the derivation across languages.
    const KAT1_PUB = Uint8Array.from(
      Buffer.from(
        '041f140146bfb1b251f84f4ddbe0d4cdcfd77afd984a9520e35794021f8312bb9eec995a08b1fa7704df3dcc0b50a9665263fb7711f95f9f8a449c5096e47c892b',
        'hex',
      ),
    );
    expect(
      deriveAccountAddress({
        factoryContractId: 'CDBOW57Z4PY3SWFMTVPODG33JC55CKDFAFPH5EVB5APVPL7KMMO5OO4X',
        credentialId: new TextEncoder().encode('democred'),
        publicKey: KAT1_PUB,
        networkPassphrase: Networks.TESTNET,
      }),
    ).toBe('CDLHJTPY4QU74EGLADUTZQCKLINANILFLE5E4OF46QJXKBA7QC7IV4KQ');
  });

  it('binds the public key into the salt (F1): a different key gives a different address', () => {
    const base = {
      factoryContractId: FACTORY,
      credentialId: CRED_DEMOCRED,
      networkPassphrase: Networks.TESTNET,
    };
    const withA = deriveAccountAddress({ ...base, publicKey: PUB_A });
    const withB = deriveAccountAddress({ ...base, publicKey: PUB_B });
    expect(withA).not.toBe(withB);
  });

  it('depends on the network passphrase (testnet vs public differ)', () => {
    const base = {
      factoryContractId: FACTORY,
      credentialId: CRED_DEMOCRED,
      publicKey: PUB_A,
    };
    const testnet = deriveAccountAddress({ ...base, networkPassphrase: Networks.TESTNET });
    const pubnet = deriveAccountAddress({ ...base, networkPassphrase: Networks.PUBLIC });
    expect(pubnet).not.toBe(testnet);
  });

  it('throws a typed KitError on a bad factory id, empty credential, or wrong-size key', () => {
    const bad = () =>
      deriveAccountAddress({
        factoryContractId: 'not-a-contract',
        credentialId: CRED_DEMOCRED,
        publicKey: PUB_A,
        networkPassphrase: Networks.TESTNET,
      });
    expect(bad).toThrow();
    try {
      bad();
    } catch (e) {
      expect(isKitError(e)).toBe(true);
    }
    try {
      deriveAccountAddress({
        factoryContractId: FACTORY,
        credentialId: new Uint8Array(0),
        publicKey: PUB_A,
        networkPassphrase: Networks.TESTNET,
      });
      throw new Error('expected throw');
    } catch (e) {
      expect(isKitError(e)).toBe(true);
    }
    try {
      deriveAccountAddress({
        factoryContractId: FACTORY,
        credentialId: CRED_DEMOCRED,
        publicKey: new Uint8Array(33), // not 65-byte SEC-1
        networkPassphrase: Networks.TESTNET,
      });
      throw new Error('expected throw');
    } catch (e) {
      expect(isKitError(e)).toBe(true);
    }
  });
});

describe('deriveSmartWalletAddress (passkey-kit v1, offline)', () => {
  // A REAL on-chain v1 deployment from scripts/v1-events-probe.ts: this deployer +
  // founding credential deployed exactly this wallet (verified: derived === deployed).
  const V1_DEPLOYER = 'GCO3Q7OMYHLFWQL7EZQNF5DHXR3PQ4TFZHBZE6MMD4B3QMMCV3TZNFIT';
  const V1_CRED = encodeChallenge(
    Uint8Array.from(Buffer.from('401017927d529605e32979bad2e1534c', 'hex')),
  );
  const V1_WALLET = 'CDXICVKLHPPAZ3EM65OESOGBSQE4YQGFN6JK7ICPYUXDAQPAVXBZ4PAT';

  it('matches a real on-chain v1 deployment (salt = sha256(rawCredentialId))', () => {
    expect(
      deriveSmartWalletAddress({
        deployer: V1_DEPLOYER,
        credentialId: V1_CRED,
        networkPassphrase: Networks.TESTNET,
      }),
    ).toBe(V1_WALLET);
  });

  it('is deterministic and depends on deployer, credential, and network', () => {
    const base = {
      deployer: V1_DEPLOYER,
      credentialId: V1_CRED,
      networkPassphrase: Networks.TESTNET,
    };
    expect(deriveSmartWalletAddress(base)).toBe(deriveSmartWalletAddress(base));
    // Different deployer → different wallet (unlike our single-signer factory scheme).
    const otherDeployer = deriveSmartWalletAddress({
      ...base,
      deployer: 'GBISW7YZ57FZPSJYQV3YJTM4XYKQ4HWTUTCQ2RIF2VVEZVM26F544M5F',
    });
    expect(otherDeployer).not.toBe(V1_WALLET);
    expect(deriveSmartWalletAddress({ ...base, networkPassphrase: Networks.PUBLIC })).not.toBe(
      V1_WALLET,
    );
  });

  it('uses RAW credential bytes for the salt — distinct from the factory (utf8) scheme', () => {
    // deriveAccountAddress salts sha256(utf8(base64url string)); deriveSmartWalletAddress
    // salts sha256(rawBytes). Same inputs must NOT collide.
    const raw = Uint8Array.from(Buffer.from('401017927d529605e32979bad2e1534c', 'hex'));
    const asFactory = deriveAccountAddress({
      factoryContractId: 'CBVGSJEIKGQ6MYFOWCBNV2NLLPJJV757UP6QQV6FDTI4S3N72OZ676TM',
      credentialId: new TextEncoder().encode(encodeChallenge(raw)),
      publicKey: PUB_A,
      networkPassphrase: Networks.TESTNET,
    });
    expect(asFactory).not.toBe(V1_WALLET);
  });

  it('throws a typed KitError on an empty credential id', () => {
    try {
      deriveSmartWalletAddress({
        deployer: V1_DEPLOYER,
        credentialId: '',
        networkPassphrase: Networks.TESTNET,
      });
      throw new Error('expected throw');
    } catch (e) {
      expect(isKitError(e)).toBe(true);
    }
  });
});
