import { defineConfig } from 'vitepress';
import { withMermaid } from 'vitepress-plugin-mermaid';

// The single docs site: adopter front door (quickstart / integration / API) +
// the living compatibility matrix (S09) + CI architecture (S10).
export default withMermaid(
  defineConfig({
    title: 'Stellar Passkey',
    description:
      'Passkey sign-in for Stellar smart accounts — a minimal ES256-only SDK, a stellar-wallets-kit module, and a living WebAuthn compatibility matrix.',
    // matrix-table.md is a generated partial included into matrix.md, not its own page.
    srcExclude: ['matrix-table.md'],
    // The API reference under /api is generated by typedoc; its cross-links and
    // external type references shouldn't fail the build.
    ignoreDeadLinks: true,
    themeConfig: {
      nav: [
        { text: 'Quickstart', link: '/quickstart' },
        { text: 'Integrate', link: '/integration' },
        { text: 'API', link: '/api/' },
        { text: 'Matrix', link: '/matrix' },
        { text: 'Security', link: '/security' },
      ],
      sidebar: [
        {
          text: 'Guide',
          items: [
            { text: 'Quickstart', link: '/quickstart' },
            { text: 'Integration (wallet teams)', link: '/integration' },
            { text: 'Security & recovery', link: '/security' },
          ],
        },
        {
          text: 'Reference',
          items: [
            { text: 'API reference', link: '/api/' },
            { text: 'Compatibility matrix', link: '/matrix' },
            { text: 'CI architecture', link: '/architecture' },
            { text: 'Contributing cells', link: '/CONTRIBUTING' },
          ],
        },
      ],
      search: { provider: 'local' },
      outline: 'deep',
    },
  }),
);
