/**
 * S09 (YK-435) — the matrix builder. Merges the BCD static snapshot (S05) with
 * the virtual-authenticator CI snapshot (S07) into one dated, diffable matrix
 * where every cell is tagged with `source` + `tier` (S08) + `lastVerified`.
 * CI (machine-verified) overrides BCD/curated for the same cell. Writes
 * `data/matrix.<ISODATE>.json` (+ pointer) and renders `site/matrix-table.md`.
 * The live "your device" overlay (S06) is applied client-side in the site.
 * Run with `pnpm matrix:build`.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CiSnapshotSchema,
  MATRIX_SCHEMA_VERSION,
  MatrixSnapshotSchema,
  MergedMatrixSnapshotSchema,
  type MergedCell,
} from '../src/matrixSchema';
import { tierFor } from '../src/tiers';

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, '..', 'data');
const siteDir = join(here, '..', 'site');
const builtAt = process.env.MATRIX_PULL_DATE ?? new Date().toISOString().slice(0, 10);

function latestFile(prefix: string): string | null {
  const files = readdirSync(dataDir)
    .filter((f) => f.startsWith(prefix) && f.endsWith('.json'))
    .sort();
  return files.at(-1) ?? null;
}
function readJson(file: string): unknown {
  return JSON.parse(readFileSync(join(dataDir, file), 'utf8'));
}

// ── inputs ───────────────────────────────────────────────────────────────────
const bcdFile = latestFile('bcd.');
const ciFile = latestFile('ci.');
const bcd = bcdFile ? MatrixSnapshotSchema.parse(readJson(bcdFile)) : null;
const ci = ciFile ? CiSnapshotSchema.parse(readJson(ciFile)) : null;

const cellKey = (feature: string, browser: string, os: string): string =>
  `${feature}|${browser}|${os}`;
const cells = new Map<string, MergedCell>();

function upsert(cell: Omit<MergedCell, 'tier'>): void {
  cells.set(cellKey(cell.feature, cell.browser, cell.os), {
    ...cell,
    tier: tierFor(cell.browser, cell.os).tier,
  });
}

// 1. BCD / curated / passkeys.dev rows (the static baseline).
if (bcd) {
  for (const row of bcd.rows) {
    upsert({
      feature: row.feature,
      featureLabel: row.featureLabel,
      browser: row.browser,
      os: row.os,
      status: row.status,
      source: row.source,
      lastVerified: row.pulledAt,
      since: row.since,
      ...(row.notes ? { notes: row.notes } : {}),
      ...(row.sourceUrl ? { sourceUrl: row.sourceUrl } : {}),
    });
  }
}

// 2. CI rows override matching cells. The harness reports the engine on the
//    runner OS; map it onto the matrix's desktop browser+OS cells.
const CI_BROWSER_MAP: Record<string, { browser: string; os: string }> = {
  Chromium: { browser: 'Chrome', os: 'desktop' },
  Chrome: { browser: 'Chrome', os: 'desktop' },
  Edge: { browser: 'Edge', os: 'Windows' },
};
if (ci) {
  for (const row of ci.rows) {
    const mapped = CI_BROWSER_MAP[row.browser];
    if (!mapped) continue;
    upsert({
      feature: row.feature,
      featureLabel: row.featureLabel,
      browser: mapped.browser,
      os: mapped.os,
      status: row.status,
      source: 'ci',
      lastVerified: row.pulledAt,
      ...(row.notes ? { notes: row.notes } : {}),
    });
  }
}

const mergedCells = [...cells.values()].sort(
  (a, b) =>
    a.feature.localeCompare(b.feature) ||
    a.browser.localeCompare(b.browser) ||
    a.os.localeCompare(b.os),
);

const features = bcd
  ? bcd.features.map((f) => ({ id: f.id, label: f.label }))
  : [...new Set(mergedCells.map((c) => c.feature))].map((id) => ({ id, label: id }));

const snapshot = MergedMatrixSnapshotSchema.parse({
  schemaVersion: MATRIX_SCHEMA_VERSION,
  builtAt,
  inputs: { bcd: bcdFile, ci: ciFile },
  features,
  cells: mergedCells,
});

mkdirSync(dataDir, { recursive: true });
const file = `matrix.${builtAt}.json`;
writeFileSync(join(dataDir, file), JSON.stringify(snapshot, null, 2) + '\n');
writeFileSync(
  join(dataDir, 'matrix-latest.json'),
  JSON.stringify(
    { latestSnapshot: file, builtAt, cellCount: mergedCells.length, inputs: snapshot.inputs },
    null,
    2,
  ) + '\n',
);

// ── render the markdown grid the VitePress site includes ─────────────────────
const STATUS_ICON: Record<string, string> = {
  supported: '✅',
  unsupported: '❌',
  partial: '🟡',
  unknown: '❔',
};
const TIER_LABEL: Record<string, string> = {
  'tier-1-automated': 'T1 · automated',
  'tier-2-manual': 'T2 · manual',
};
const featureLabel = (id: string): string => features.find((f) => f.id === id)?.label ?? id;

let md = `<!-- GENERATED by \`pnpm matrix:build\` on ${builtAt}. Do not edit by hand. -->\n`;
md += `_Built ${builtAt} from ${bcdFile ?? '(no BCD)'} + ${ciFile ?? '(no CI)'}._\n`;
for (const feature of features) {
  const rows = mergedCells.filter((c) => c.feature === feature.id);
  if (rows.length === 0) continue;
  md += `\n### ${featureLabel(feature.id)}\n\n`;
  md += `| Browser / OS | Status | Source | Tier | Last verified |\n`;
  md += `| --- | --- | --- | --- | --- |\n`;
  for (const c of rows) {
    const icon = STATUS_ICON[c.status] ?? '';
    md += `| ${c.browser} / ${c.os} | ${icon} ${c.status} | \`${c.source}\` | ${TIER_LABEL[c.tier] ?? c.tier} | ${c.lastVerified} |\n`;
  }
}

mkdirSync(siteDir, { recursive: true });
writeFileSync(join(siteDir, 'matrix-table.md'), md);

console.log(
  `matrix:build → ${file}: ${String(mergedCells.length)} cells from bcd=${bcdFile ?? '–'} ci=${ciFile ?? '–'}; rendered site/matrix-table.md`,
);
