/**
 * S09 (YK-435) — the matrix DIFF. Compares the two most recent dated snapshots
 * (`data/matrix.<ISODATE>.json`) and reports what changed between them: cells
 * added, removed, or whose **status / source / tier** moved. This is what makes
 * the matrix genuinely *diffable over time* — staleness and real-world drift are
 * visible in history, not asserted. `lastVerified` (which advances every build)
 * is intentionally ignored so the diff shows substance, not date churn.
 *
 * Writes `site/matrix-diff.md` (rendered into the site) + a machine-readable
 * `data/matrix-diff.<from>..<to>.json`, and prints a one-line summary.
 * Run with `pnpm matrix:diff`.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MergedMatrixSnapshotSchema, type MergedCell } from '../src/matrixSchema';

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, '..', 'data');
const renderedDir = join(here, '..', 'rendered');

const snapshots = readdirSync(dataDir)
  .filter((f) => /^matrix\.\d{4}-\d{2}-\d{2}\.json$/.test(f))
  .sort();

const key = (c: MergedCell): string => `${c.feature}|${c.browser}|${c.os}`;
const fingerprint = (c: MergedCell): string => `${c.status}|${c.source}|${c.tier}`;
const cellMap = (file: string): Map<string, MergedCell> => {
  const snap = MergedMatrixSnapshotSchema.parse(JSON.parse(readFileSync(join(dataDir, file), 'utf8')));
  return new Map(snap.cells.map((c) => [key(c), c]));
};

if (snapshots.length < 2) {
  const md = `<!-- GENERATED by \`pnpm matrix:diff\`. -->\n_Only one dated snapshot exists so far — a diff appears once a second snapshot lands._\n`;
  mkdirSync(renderedDir, { recursive: true });
  writeFileSync(join(renderedDir, 'matrix-diff.md'), md);
  console.log('matrix:diff → only one snapshot; nothing to diff yet.');
  process.exit(0);
}

const fromFile = snapshots.at(-2)!;
const toFile = snapshots.at(-1)!;
const from = cellMap(fromFile);
const to = cellMap(toFile);
const dateOf = (f: string): string => f.replace(/^matrix\.|\.json$/g, '');

const added: MergedCell[] = [];
const removed: MergedCell[] = [];
const changed: { key: string; before: MergedCell; after: MergedCell }[] = [];

for (const [k, after] of to) {
  const before = from.get(k);
  if (!before) added.push(after);
  else if (fingerprint(before) !== fingerprint(after)) changed.push({ key: k, before, after });
}
for (const [k, before] of from) if (!to.has(k)) removed.push(before);

const total = added.length + removed.length + changed.length;
const cell = (c: MergedCell): string => `${c.featureLabel} · ${c.browser}/${c.os}`;
const fp = (c: MergedCell): string => `${c.status} · \`${c.source}\` · ${c.tier}`;

let md = `<!-- GENERATED by \`pnpm matrix:diff\`. Do not edit by hand. -->\n`;
md += `_Diff **${dateOf(fromFile)} → ${dateOf(toFile)}**: ${String(total)} change(s)._\n`;
if (total === 0) {
  md += `\nNo cell changed status, source, or verification tier between these two snapshots. The matrix is current.\n`;
} else {
  if (changed.length) {
    md += `\n### Changed (${String(changed.length)})\n\n| Cell | Before | After |\n| --- | --- | --- |\n`;
    for (const c of changed) md += `| ${cell(c.after)} | ${fp(c.before)} | ${fp(c.after)} |\n`;
  }
  if (added.length) {
    md += `\n### Added (${String(added.length)})\n\n| Cell | Now |\n| --- | --- |\n`;
    for (const c of added) md += `| ${cell(c)} | ${fp(c)} |\n`;
  }
  if (removed.length) {
    md += `\n### Removed (${String(removed.length)})\n\n| Cell | Was |\n| --- | --- |\n`;
    for (const c of removed) md += `| ${cell(c)} | ${fp(c)} |\n`;
  }
}

mkdirSync(renderedDir, { recursive: true });
writeFileSync(join(renderedDir, 'matrix-diff.md'), md);
const diffJson = {
  from: dateOf(fromFile),
  to: dateOf(toFile),
  added: added.map((c) => ({ cell: key(c), now: fingerprint(c) })),
  removed: removed.map((c) => ({ cell: key(c), was: fingerprint(c) })),
  changed: changed.map((c) => ({ cell: c.key, before: fingerprint(c.before), after: fingerprint(c.after) })),
};
writeFileSync(
  join(dataDir, `matrix-diff.${dateOf(fromFile)}..${dateOf(toFile)}.json`),
  JSON.stringify(diffJson, null, 2) + '\n',
);

console.log(
  `matrix:diff → ${dateOf(fromFile)} → ${dateOf(toFile)}: ${String(total)} change(s) (` +
    `${String(changed.length)} changed, ${String(added.length)} added, ${String(removed.length)} removed); wrote rendered/matrix-diff.md`,
);
