/**
 * The matrix DIFF. Compares the two most recent dated snapshots
 * (`data/matrix.<ISODATE>.json`) and reports what changed: cells added, removed,
 * or whose **status / source / tier** moved (substance), plus cells that held
 * their status but were **re-verified on a newer engine version** (the
 * anti-staleness "still true on the newer browser" signal). `lastVerified` dates
 * are ignored so the diff shows substance, not churn.
 *
 * Writes `rendered/matrix-diff.md` + a machine-readable
 * `data/matrix-diff.<from>..<to>.json`, and prints a one-line summary.
 * Run with `pnpm matrix:diff`.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MergedMatrixSnapshotSchema } from '../src/matrixSchema';
import { diffChangeCount, diffSnapshots } from '../src/pipeline';

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = process.env.MATRIX_DATA_DIR ?? join(here, '..', 'data');
const renderedDir = process.env.MATRIX_RENDERED_DIR ?? join(here, '..', 'rendered');

const snapshots = readdirSync(dataDir)
  .filter((f) => /^matrix\.\d{4}-\d{2}-\d{2}\.json$/.test(f))
  .sort();
const dateOf = (f: string): string => f.replace(/^matrix\.|\.json$/g, '');
const load = (file: string): ReturnType<typeof MergedMatrixSnapshotSchema.parse> =>
  MergedMatrixSnapshotSchema.parse(JSON.parse(readFileSync(join(dataDir, file), 'utf8')));

mkdirSync(renderedDir, { recursive: true });

if (snapshots.length < 2) {
  const md = `<!-- GENERATED by \`pnpm matrix:diff\`. -->\n_Only one dated snapshot exists so far — a diff appears once a second snapshot lands._\n`;
  writeFileSync(join(renderedDir, 'matrix-diff.md'), md);
  console.log('matrix:diff → only one snapshot; nothing to diff yet.');
  process.exit(0);
}

const fromFile = snapshots.at(-2) as string;
const toFile = snapshots.at(-1) as string;
const diff = diffSnapshots(load(fromFile), load(toFile), dateOf(fromFile), dateOf(toFile));
const total = diffChangeCount(diff);
const nice = (cell: string): string => cell.replace(/\|/g, ' · ');

let md = `<!-- GENERATED by \`pnpm matrix:diff\`. Do not edit by hand. -->\n`;
md += `_Diff **${diff.from} → ${diff.to}**: ${String(total)} substantive change(s), ${String(diff.reverified.length)} re-verification(s)._\n`;
if (total === 0 && diff.reverified.length === 0) {
  md += `\nNo cell changed status, source, or verification tier between these two snapshots. The matrix is current.\n`;
} else {
  if (diff.changed.length) {
    md += `\n### Changed (${String(diff.changed.length)})\n\n| Cell | Before | After |\n| --- | --- | --- |\n`;
    for (const c of diff.changed) md += `| ${nice(c.cell)} | ${c.before} | ${c.after} |\n`;
  }
  if (diff.added.length) {
    md += `\n### Added (${String(diff.added.length)})\n\n| Cell | Now |\n| --- | --- |\n`;
    for (const c of diff.added) md += `| ${nice(c.cell)} | ${c.now} |\n`;
  }
  if (diff.removed.length) {
    md += `\n### Removed (${String(diff.removed.length)})\n\n| Cell | Was |\n| --- | --- |\n`;
    for (const c of diff.removed) md += `| ${nice(c.cell)} | ${c.was} |\n`;
  }
  if (diff.reverified.length) {
    md += `\n### Re-verified on a newer engine (${String(diff.reverified.length)})\n\n`;
    md += `_Status unchanged — the same result reproduced on a newer browser build._\n\n`;
    md += `| Cell | From | To |\n| --- | --- | --- |\n`;
    for (const c of diff.reverified)
      md += `| ${nice(c.cell)} | ${c.fromVersion} | ${c.toVersion} |\n`;
  }
}
writeFileSync(join(renderedDir, 'matrix-diff.md'), md);
writeFileSync(
  join(dataDir, `matrix-diff.${diff.from}..${diff.to}.json`),
  JSON.stringify(diff, null, 2) + '\n',
);

console.log(
  `matrix:diff → ${diff.from} → ${diff.to}: ${String(total)} change(s) ` +
    `(${String(diff.changed.length)} changed, ${String(diff.added.length)} added, ${String(diff.removed.length)} removed), ` +
    `${String(diff.reverified.length)} re-verification(s); wrote rendered/matrix-diff.md`,
);
